### ISSUE TITLE
run error on windows

### ISSUE THREAD

**Issue by beining1234** [ddcw/ibd2sql#1]
windows 环境运行报page_type错误，帮忙看下，感谢。
python.exe c:/work/0.5.Source/python/ibd2sql-main/main.py
Traceback (most recent call last):
  File "c:\work\0.5.Source\python\ibd2sql-main\main.py", line 3, in <module>
    import innodb_fil
  File "c:\work\0.5.Source\python\ibd2sql-main\innodb_fil.py", line 1, in <module>
    import page_type
ModuleNotFoundError: No module named 'page_type'

**Comment by ddcw** [comment]
> windows 环境运行报page_type错误，帮忙看下，感谢。 python.exe c:/work/0.5.Source/python/ibd2sql-main/main.py Traceback (most recent call last): File "c:\work\0.5.Source\python\ibd2sql-main\main.py", line 3, in import innodb_fil File "c:\work\0.5.Source\python\ibd2sql-main\innodb_fil.py", line 1, in import page_type ModuleNotFoundError: No module named 'page_type'

抱歉, 忘记 add `page_type.py`了, 之前只add innodb*, 后面又add了main.py, 但忘记add page_type.py了, 
现在已经添加了, 你重新下载试下呢 -_-

`page_type.py`是使用的mysql官方的storage/innobase/include/fil0fil.h

**Comment by beining1234** [comment]
收到，感谢啊，程序蛮好用的。期待后续的工具迭代。


Thanks,
李贝宁
















在 2023-07-19 15:10:26，"ddcw" ***@***.***> 写道：

windows 环境运行报page_type错误，帮忙看下，感谢。 python.exe c:/work/0.5.Source/python/ibd2sql-main/main.py Traceback (most recent call last): File "c:\work\0.5.Source\python\ibd2sql-main\main.py", line 3, in import innodb_fil File "c:\work\0.5.Source\python\ibd2sql-main\innodb_fil.py", line 1, in import page_type ModuleNotFoundError: No module named 'page_type'

抱歉, 忘记 add page_type.py了, 之前只add innodb*, 后面又add了main.py, 但忘记add page_type.py了,
现在已经添加了, 你重新下载试下呢 -_-

page_type.py是使用的mysql官方的storage/innobase/include/fil0fil.h
