### ISSUE TITLE
--sql 参数解析idb数据  varchar、text、int 、bigint类型解析出的数据有问题！

### ISSUE THREAD

**Issue by yikela1990** [ddcw/ibd2sql#12]
1、表结构
<img width="1086" alt="image" src="https://github.com/ddcw/ibd2sql/assets/76995384/9557ec74-0fd6-44d3-9f3b-2356fbccf891">

2、先查一下真实数据是什么
<img width="781" alt="image" src="https://github.com/ddcw/ibd2sql/assets/76995384/c98ed474-c0e3-4f87-9f58-bba50368d50c">

3、使用ibd2sql解析数据
$ python3.6 main.py  /data0/mysqlsandbox/data/sandboxes/msb_8_0_33/data/testdb/dts_test_table.ibd --sql > /data0/dts_test_table.sql

4、看一下dts_test_table.sql里的id=100063数据是什么
<img width="1560" alt="image" src="https://github.com/ddcw/ibd2sql/assets/76995384/cfc627d1-1602-4cbb-b453-cbff772a2cff">

**Comment by yikela1990** [comment]
版本：
<img width="440" alt="image" src="https://github.com/ddcw/ibd2sql/assets/76995384/12e8178f-42b8-40ab-b921-0af7dbcf6dab">

**Comment by ddcw** [comment]
> 1、表结构 <img alt="image" width="1086" src="https://private-user-images.githubusercontent.com/76995384/321143390-9557ec74-0fd6-44d3-9f3b-2356fbccf891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzQ4NzIsIm5iZiI6MTcxMjczNDU3MiwicGF0aCI6Ii83Njk5NTM4NC8zMjExNDMzOTAtOTU1N2VjNzQtMGZkNi00NGQzLTlmM2ItMjM1NmZiY2NmODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOTVlYmFlMjVhYjFkMzQyY2FmNjU5ZWI0NjRkMTQ5ODU2YWFhMWU0MDg5NzliMDdiMjg0YzhkYjM1OWQ4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N5Y2FEvWVOuU7oV0MRYtomOmaBcayK9NPc7901tpZ1U">
> 
> 2、先查一下真实数据是什么 <img alt="image" width="781" src="https://private-user-images.githubusercontent.com/76995384/321143635-c98ed474-c0e3-4f87-9f58-bba50368d50c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzQ4NzIsIm5iZiI6MTcxMjczNDU3MiwicGF0aCI6Ii83Njk5NTM4NC8zMjExNDM2MzUtYzk4ZWQ0NzQtYzBlMy00Zjg3LTlmNTgtYmJhNTAzNjhkNTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjgwYzk2NzllNDA4YjZmNDQ3NzljNjQ0MTE5YmExNjYyNDlkN2RlOTUxMDg3YjdmZTBiYzFkYWJhYmQxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FRG5KemQ3Jlo5_MqUqyVK4yTcvMoHTJsXUZp550spI">
> 
> 3、使用ibd2sql解析数据 $ python3.6 main.py /data0/mysqlsandbox/data/sandboxes/msb_8_0_33/data/testdb/dts_test_table.ibd --sql > /data0/dts_test_table.sql
> 
> 4、看一下dts_test_table.sql里的id=100063数据是什么 <img alt="image" width="1560" src="https://private-user-images.githubusercontent.com/76995384/321144088-cfc627d1-1602-4cbb-b453-cbff772a2cff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzQ4NzIsIm5iZiI6MTcxMjczNDU3MiwicGF0aCI6Ii83Njk5NTM4NC8zMjExNDQwODgtY2ZjNjI3ZDEtMTYwMi00Y2JiLWI0NTMtY2JmZjc3MmEyY2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YjNiZTEzMjI2ZjhhZGFiN2ZlYmI1Y2YzOThiMjAyNDA1MjI0Y2M3Y2ExZmJmMmRkZTViNDFmZTI2YmYzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LI26X16DGMnDpfiQ43Np5EcS35MKAtcMLDp4ixBVFVY">

1. ibd2sql是否为最新版呢 ?  (我好像处理过类似的问题).
2. 提供下DDL和测试数据, 我复现下. 非图片版的(我懒得敲-_-)
3. 也可以提供下 --debug 的日志

**Comment by yikela1990** [comment]
1、代码是直接clone的main分支的代码。
2、测试数据不好提供，因为我使用相同的表结构、插入了一条数据，然后再使用ibd2sql 导出data是没有任何问题的，您留一个邮箱，我把ibd文件发给你，这个表是纯测试数据，没有我们自己的数据。
3、debug日志：
[debug.zip](https://github.com/ddcw/ibd2sql/files/14929267/debug.zip)

**Comment by ddcw** [comment]
> 1、代码是直接clone的main分支的代码。 2、测试数据不好提供，因为我使用相同的表结构、插入了一条数据，然后再使用ibd2sql 导出data是没有任何问题的，您留一个邮箱，我把ibd文件发给你，这个表是纯测试数据，没有我们自己的数据。 3、debug日志： [debug.zip](https://github.com/ddcw/ibd2sql/files/14929267/debug.zip)

纯测试数据的话, 就发这个临时邮箱吧:  7s9s6bib@qabq.com
从debug看起来像是元数据信息有问题

**Comment by yikela1990** [comment]
已发送邮箱

**Comment by ddcw** [comment]
用ibd2sql 0.3 版本可以解析, 看来是新版本引入的BUG .  我尽快修改 1.0 的这个BUG
![image](https://github.com/ddcw/ibd2sql/assets/32298386/2e83b614-25b0-4064-a807-e68e66d03047)


> 已发送邮箱

**Comment by ddcw** [comment]
> 好的 修复了以后麻烦update一下这个issuse，我再测一下

修复了, 你重新下载后, 再试下呢
修复记录:
```
# ibd2sql/innodb_page_index.py::record_header
self.instant = True
```

**Comment by yikela1990** [comment]
# python3.6 main.py /data0/dts_test_table.ibd --sql > /data0/dts_test_table.sql 
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from ibd2sql.ibd2sql import ibd2sql
  File "/root/ibd2sql-main/ibd2sql/ibd2sql.py", line 7, in <module>
    from ibd2sql.innodb_page_index import *
  File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 53
    self.instant = True
                      ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by ddcw** [comment]
> # python3.6 main.py /data0/dts_test_table.ibd --sql > /data0/dts_test_table.sql
> Traceback (most recent call last): File "main.py", line 5, in from ibd2sql.ibd2sql import ibd2sql File "/root/ibd2sql-main/ibd2sql/ibd2sql.py", line 7, in from ibd2sql.innodb_page_index import * File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 53 self.instant = True ^ TabError: inconsistent use of tabs and spaces in indentation

你clone的还是自己修改的呢,  修改的话, 我代码里面是tab 不是空格

**Comment by yikela1990** [comment]
再次运行，跑了一会就挂了
<img width="1522" alt="image" src="https://github.com/ddcw/ibd2sql/assets/76995384/ffd716cf-6b0a-4c1a-9d88-c6f0be88a801">


Traceback (most recent call last):
  File "main.py", line 177, in <module>
    ddcw.get_sql()
  File "/root/ibd2sql-main/ibd2sql/ibd2sql.py", line 229, in get_sql
    for x in _tdata:
  File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 226, in read_row
    self._read_all_row()
  File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 396, in _read_all_row
    _data[colno],_expage[colno] = self._read_field(col)
  File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 162, in _read_field
    data = self.read(size).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 53: invalid start byte

**Comment by ddcw** [comment]
> 再次运行，跑了一会就挂了 <img alt="image" width="1522" src="https://private-user-images.githubusercontent.com/76995384/321212347-ffd716cf-6b0a-4c1a-9d88-c6f0be88a801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDg2MTMsIm5iZiI6MTcxMjc0ODMxMywicGF0aCI6Ii83Njk5NTM4NC8zMjEyMTIzNDctZmZkNzE2Y2YtNmIwYS00YzFhLTlkODgtYzZmMGJlODhhODAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDExMjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZmFiMGQwOGQ3NGUwOWRlMTJmZjk2YTEwODVjZDE1YzMwYmQzZTk2NTFjMjNiNzU0MWQ2NDNhOGYyOTZlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Lu1XXeMuVoS-mD4Xl_2IknpJKvFP-gKiAoz7Zrs2FA">
> 
> Traceback (most recent call last): File "main.py", line 177, in ddcw.get_sql() File "/root/ibd2sql-main/ibd2sql/ibd2sql.py", line 229, in get_sql for x in _tdata: File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 226, in read_row self._read_all_row() File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 396, in _read_all_row _data[colno],_expage[colno] = self._read_field(col) File "/root/ibd2sql-main/ibd2sql/innodb_page_index.py", line 162, in _read_field data = self.read(size).decode() UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 53: invalid start byte

已修复, 请重新下载最新版本试下呢,  
我测试了下, 全部解析出来了. 3.3GB左右, 700W行左右数据 (可以看 /proc/PID/io 的rchar  来预估速度哈)
修复记录: recorde header 1-2bit is instant flag

**Comment by yikela1990** [comment]
greate! 👍🏻

**Comment by yikela1990** [comment]
https://cloud.tencent.com/developer/article/2407144?pos=comment

这个文章有一个地方有问题，就是推荐使用import tablespace的方式将ibd文件导入到现有数据库中
1、缺少  表名.cfg 文件
2、alter table xxx import tablespace的时候会报lscn错误

**Comment by ddcw** [comment]
1. 因为不一定是flush export 出来的ibd文件, 所以不一定有.cfg文件. (无.cfg的话, 会有warning提示, 不影响导入): 官方教程: https://dev.mysql.com/doc/refman/8.0/en/innodb-troubleshooting-datadict.html
2. 如果目标环境是新环境的话, 是可能存在lsn的问题. 而且ibd文件本身也可能存在问题. 这时候就可以使用ibd2sql来解析了.  `--page-start 100 --page-count 1` 解析指定的页


> https://cloud.tencent.com/developer/article/2407144?pos=comment
> 
> 这个文章有一个地方有问题，就是推荐使用import tablespace的方式将ibd文件导入到现有数据库中 1、缺少 表名.cfg 文件 2、alter table xxx import tablespace的时候会报lsn错误
