### ISSUE TITLE
感激，分分钟解决问题

### ISSUE THREAD

**Issue by hellyguo** [ddcw/ibd2sql#14]
用 `ibd2sql` 解决了表内数据误删问题，找回了数据。万分感谢！

一个小建议，命令的 `usage` 输出可调整一下：

```shell
usage: main.py [-h] [--version] [--ddl] [--sql] [--delete] [--complete-insert] [--force] [--set] [--multi-value] [--replace]
               [--table TABLE_NAME] [--schema SCHEMA_NAME] [--sdi-table SDI_TABLE] [--where-trx WHERE_TRX]
               [--where-rollptr WHERE_ROLLPTR] [--where WHERE] [--limit LIMIT] [--debug] [--debug-file DEBUG_FILE]
               [--page-min PAGE_MIN] [--page-max PAGE_MAX] [--page-start PAGE_START] [--page-count PAGE_COUNT]
               [--page-skip PAGE_SKIP] [--parallel PARALLEL]
               [FILENAME]
```

可改为

```shell
usage: 
main.py -h
main.py --version
main.py <FILENAME> [--ddl] [--sql] [--delete] [--complete-insert] [--force] [--set] [--multi-value] [--replace]
               [--table TABLE_NAME] [--schema SCHEMA_NAME] [--sdi-table SDI_TABLE] [--where-trx WHERE_TRX]
               [--where-rollptr WHERE_ROLLPTR] [--where WHERE] [--limit LIMIT] [--debug] [--debug-file DEBUG_FILE]
               [--page-min PAGE_MIN] [--page-max PAGE_MAX] [--page-start PAGE_START] [--page-count PAGE_COUNT]
               [--page-skip PAGE_SKIP] [--parallel PARALLEL]
```

这样与实际执行可保持一致，与 `README.md` 中的例子一致。

处置时紧张，一开始按 `usage` 中的文件名放最后方式去操作，没输出 `sql`。冷静后反复尝试才发现需要将文件名前置。

最后，再说一次，感谢！！！

**Comment by ddcw** [comment]
和**参数顺序没有关系**啊,  我后面再调整下这个帮助信息吧(添加常用例子进去). 其实`README.md`里面也有例子的.
你把顺序有问题无法解析的**截图**(打码)发我一下呢. 还有python的版本
![image](https://github.com/ddcw/ibd2sql/assets/32298386/b3a239d5-4eff-47c0-bde1-21e1325c2c98)


> 用 `ibd2sql` 解决了表内数据误删问题，找回了数据。万分感谢！
> 
> 一个小建议，命令的 `usage` 输出可调整一下：
> 
> ```shell
> usage: main.py [-h] [--version] [--ddl] [--sql] [--delete] [--complete-insert] [--force] [--set] [--multi-value] [--replace]
>                [--table TABLE_NAME] [--schema SCHEMA_NAME] [--sdi-table SDI_TABLE] [--where-trx WHERE_TRX]
>                [--where-rollptr WHERE_ROLLPTR] [--where WHERE] [--limit LIMIT] [--debug] [--debug-file DEBUG_FILE]
>                [--page-min PAGE_MIN] [--page-max PAGE_MAX] [--page-start PAGE_START] [--page-count PAGE_COUNT]
>                [--page-skip PAGE_SKIP] [--parallel PARALLEL]
>                [FILENAME]
> ```
> 
> 可改为
> 
> ```shell
> usage: 
> main.py -h
> main.py --version
> main.py <FILENAME> [--ddl] [--sql] [--delete] [--complete-insert] [--force] [--set] [--multi-value] [--replace]
>                [--table TABLE_NAME] [--schema SCHEMA_NAME] [--sdi-table SDI_TABLE] [--where-trx WHERE_TRX]
>                [--where-rollptr WHERE_ROLLPTR] [--where WHERE] [--limit LIMIT] [--debug] [--debug-file DEBUG_FILE]
>                [--page-min PAGE_MIN] [--page-max PAGE_MAX] [--page-start PAGE_START] [--page-count PAGE_COUNT]
>                [--page-skip PAGE_SKIP] [--parallel PARALLEL]
> ```
> 
> 这样与实际执行可保持一致，与 `README.md` 中的例子一致。
> 
> 处置时紧张，一开始按 `usage` 中的文件名放最后方式去操作，没输出 `sql`。冷静后反复尝试才发现需要将文件名前置。
> 
> 最后，再说一次，感谢！！！

**Comment by hellyguo** [comment]
事后重试，确实无区别，当时应该是太紧张了。非常感谢这个工具。
