### ISSUE TITLE
 --ddl  生成错的 `!hidden!_dropped_v1_p13_status`  NULL, 这怎么解决

### ISSUE THREAD

**Issue by xzw521** [ddcw/ibd2sql#19]
修改一下能用了
for colid in self.column:
			# ------
			col = self.column[colid]
			if '!hidden!' in col['name']:
				continue
			ddl += self._ci
			# ---------
			ddl += f"`{col['name']}` {col['type']}" #column name
			if self.COLUMN_COLL and col['type'] != 'int':

**Comment by xzw521** [comment]
`!hidden!_dropped_v1_p18_del_flag`  NULL,

**Comment by xzw521** [comment]
执行 --ddl，应该是之前删除的字段

**Comment by ddcw** [comment]
> 执行 --ddl，应该是之前删除的字段

已修复, 感谢反馈
