### ISSUE TITLE
你好，没有看到任何数据，在8.0里面生成的ibd 库名也要对应吗，我是从5.7导出create语句，在8.0执行的

### ISSUE THREAD

**Issue by knight-xiaolu2023** [ddcw/ibd2sql#21]
![image](https://github.com/ddcw/ibd2sql/assets/131353676/55400d6d-41c1-4eb4-b3bb-e382e9533c84)
![image](https://github.com/ddcw/ibd2sql/assets/131353676/48eb06ee-04ff-4c46-85fa-d00c23532479)

**Comment by ddcw** [comment]
> ![image](https://private-user-images.githubusercontent.com/131353676/335015746-55400d6d-41c1-4eb4-b3bb-e382e9533c84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzUyMDQsIm5iZiI6MTcxNzAzNDkwNCwicGF0aCI6Ii8xMzEzNTM2NzYvMzM1MDE1NzQ2LTU1NDAwZDZkLTQxYzEtNGViNC1iM2JiLWUzODJlOTUzM2M4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwMjA4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTdhYjQ0NGJlYmJkZWQyYzQxM2Q4MWFiNzQ3MTY5ZjNjMmQwMWFjNTZkMTBjMzU0ZWIxODgwZWMwNjliODBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LDs2nU2ZCZ3L2SE2uHONYFxuZH9uPPLoJFmSiO6LJ0M) ![image](https://private-user-images.githubusercontent.com/131353676/335015786-48eb06ee-04ff-4c46-85fa-d00c23532479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzUyMDQsIm5iZiI6MTcxNzAzNDkwNCwicGF0aCI6Ii8xMzEzNTM2NzYvMzM1MDE1Nzg2LTQ4ZWIwNmVlLTA0ZmYtNGM0Ni04NWZhLWQwMGMyMzUzMjQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwMjA4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmE3NDVkZjUxOTQ3ZTFiZWRkNTk5YzA4NzkzNTMyMmU4OTU4ZGJmNzdmMGYyZmFkYjAyZTgwZjVmMGY4MTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DpwsAGO8OjaOLlbW1g9aaZcPyktHP3FeYZrEKUgi3T4)

1. 库名不需要对应. 
2. 没有数据是因为 解析得到的leaf page=0  可能跟mysql版本有关系. 请提供下mysql的版本

解决办法: 
方法1:  修改脚本指定leaf_page为3. msyql 5.7通常为3.
  `vim ibd2sql/ibd2sql.py` 在141行添加 self.first_leaf_page = 3
```python3
                self.debug("FIRST LEAF PAGE ID:",self.first_leaf_page )
                self.first_leaf_page = 3
```
方法2: 每页都解析, 即强制解析, 可参考如下shell:
```shell
sditablename="/xxx/ddcw_alltype_table.ibd" # --sdi-table要指定的表名
filename="/tmp/ddcw_alltype_table.ibd" # 要解析的ibd文件名
filesize=`stat -c %s ${filename}`
maxpagecount=$[ ${filesize} / 16384 ]
current_page=1
while [ ${current_page} -le ${maxpagecount} ];do
        echo "-- ${filename} PAGE NO: ${current_page}";
        current_page=$[ ${current_page} + 1 ]
        python3 main.py ${filename} --sdi-table ${sditablename} --sql --delete --page-start ${current_page} --page-count 1 2>/dev/null ;
done
```

**Comment by knight-xiaolu2023** [comment]
好的，我试试

**Comment by knight-xiaolu2023** [comment]
![image](https://github.com/ddcw/ibd2sql/assets/131353676/987a90a2-b2f7-4260-a913-eea287e7bba6)

![image](https://github.com/ddcw/ibd2sql/assets/131353676/40005d0b-3cb5-4ed5-aa12-caeac6855a32)
你好照上面的还是无法读取数据，我这边的数据都是delete了的

**Comment by knight-xiaolu2023** [comment]
mysql版本是5.7

**Comment by knight-xiaolu2023** [comment]
使用第2种方法有数据出来

**Comment by knight-xiaolu2023** [comment]
你好有数据出来 ，但是我看有报错
![image](https://github.com/ddcw/ibd2sql/assets/131353676/f8319d88-fd41-44d4-a837-5fbaf09feceb)

**Comment by ddcw** [comment]
> 你好有数据出来 ，但是我看有报错 ![image](https://private-user-images.githubusercontent.com/131353676/335975959-f8319d88-fd41-44d4-a837-5fbaf09feceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDAxMDUsIm5iZiI6MTcxNzM5OTgwNSwicGF0aCI6Ii8xMzEzNTM2NzYvMzM1OTc1OTU5LWY4MzE5ZDg4LWZkNDEtNDRkNC1hODM3LTVmYmFmMDlmZWNlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwNzMwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjExZTUzNWRiZjk2NjdjMjYzYTViY2RkYjkyNzhlZDUwYzc5ZDZmZjk0MDRiZDY4N2JjZjBhMmI5ZTQ4MTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DMFmiulFxh27ygv55QKpz-FHOosKoG-WWdnM3LvYPDA)

强制解析, 没有做PAGE判断, 所以要去掉 标准错误 `--page-count 1 2>/dev/null`
