### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by prakash2813** [ddcw/ibd2sql#32]
Hi, I tried to parse huge 6GB Mysql 8 ibd file using command: **python main.py activity_log.ibd --force --sql --ddl --complete-insert > activity_log.sql**
But I kept getting the error: **RecursionError: maximum recursion depth exceeded**
I tried setting higher recursion limit in python using **sys.setrecursionlimit(10000)**, but still same error.
Please check the attached **stacktrace.txt** file for full stacktrace.
[stacktrace.txt](https://github.com/user-attachments/files/16596617/stacktrace.txt)

**Comment by ddcw** [comment]
It still looks like a RecursionError
1. Try a higher value, such as 1000 000
2. Use `alter table import tablespace` to import into the database for querying


When my JSON reaches layer 102, it will report an error:  `MySQL error code MY-003157 (ER-JSON_SOCUMENT-TOO-DEEP): The JSON document exceeds the maximum depth`

> Hi, I tried to parse huge 6GB Mysql 8 ibd file using command: **python main.py activity_log.ibd --force --sql --ddl --complete-insert > activity_log.sql** But I kept getting the error: **RecursionError: maximum recursion depth exceeded** I tried setting higher recursion limit in python using **sys.setrecursionlimit(10000)**, but still same error. Please check the attached **stacktrace.txt** file for full stacktrace. [stacktrace.txt](https://github.com/user-attachments/files/16596617/stacktrace.txt)

**Comment by ddcw** [comment]
There is a high probability that there are bad blocks, and your approach is correct (-- force was originally designed in this way) Another way to [handle bad blocks](https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md#ibd%E6%96%87%E4%BB%B6%E6%8D%9F%E5%9D%8F%E7%9A%84%E5%9C%BA%E6%99%AF) is to parse them page by page For example:
```shell
filename="/tmp/ddcw_alltype_table.ibd" # 要解析的ibd文件名
python3 main.py ${filename} --ddl # 获取表结构信息
filesize=`stat -c %s ${filename}`
maxpagecount=$[ ${filesize} / 16384 ]
current_page=1
while [ ${current_page} -le ${maxpagecount} ];do
	echo "-- ${filename} PAGE NO: ${current_page}"; 
	current_page=$[ ${current_page} + 1 ]
	python3 main.py ${filename} --sql --page-start ${current_page} --page-count 1 2>/dev/null ; 
done
```

The following Python code can be used to check for bad blocks:
```python
import os
filename = "/data/mysql_3314/mysqldata/db1/t20240605.ibd"
with open(filename,'rb') as f:
	for pageno in range(int(os.stat(filename).st_size/16384)):
		data = f.read(16384)
		if data[:4] != data[-8:-4]:
			print('BAD BLOCK:',pageno)
```
