### ISSUE TITLE
我的原数据里面有emoji表情字符，原表的字符集是utf8mb4，在生成insert语句的时候gbk编码报错

### ISSUE THREAD

**Issue by 1vanLuo** [ddcw/ibd2sql#33]
![image](https://github.com/user-attachments/assets/135109ec-0100-4135-b3fb-457135198603)

**Comment by ddcw** [comment]
看起来你使用的是 **v1.1**版本, 请使用最新版本(v1.5)试下呢

> ![image](https://private-user-images.githubusercontent.com/29398278/361905346-135109ec-0100-4135-b3fb-457135198603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDg0NDEsIm5iZiI6MTcyNDgwODE0MSwicGF0aCI6Ii8yOTM5ODI3OC8zNjE5MDUzNDYtMTM1MTA5ZWMtMDEwMC00MTM1LWIzZmItNDU3MTM1MTk4NjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAxMjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NGQ4OWNlZDEwN2QzOTZlMjYyNDEzMjYzNzZjYjEwYTVkNGVjY2MyN2UyMWNmN2UxMjEwOWIxZjJjMmY2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f9ZLG6pKZoD02P2LjXNpvppbDZ9Jh5QSvuaQD80smDo)

**Comment by 1vanLuo** [comment]
v1.5 的也报错呢
![4f7453b93991ac8ec310c925a95a38e](https://github.com/user-attachments/assets/87b3b765-65bc-4326-b137-7fee5b14d1a7)

**Comment by ddcw** [comment]
这报错应该是输出信息的时候编码问题,  应该是windows默认的是gbk编码导致的, win7/winserver 20212环境吗? 显示设置下编码试下呢.
编辑`main.py`文件, 添加如下信息 (print调的sys.stdout)
```python
import sys,io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
```

> v1.5 的也报错呢 ![4f7453b93991ac8ec310c925a95a38e](https://private-user-images.githubusercontent.com/29398278/362097214-87b3b765-65bc-4326-b137-7fee5b14d1a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTQ0NDMsIm5iZiI6MTcyNDgxNDE0MywicGF0aCI6Ii8yOTM5ODI3OC8zNjIwOTcyMTQtODdiM2I3NjUtNjViYy00MzI2LWIxMzctN2ZlZTViMTRkMWE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNWI0ZDE2YzRhNTlhMTlhZDdkMmE3OWI4ZjAzYmRkOTQ5MmJkNDA4YzJkNDllN2E4ZDAyN2E5ZjVkZGE3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ZGoNO_9SDK9iSoLjkTN_KquJhYJccFyKdqMh3vCAUk)

**Comment by ddcw** [comment]
应该是生僻字吧, 我这里emoji是能正常显示的, 但你那个字符却显示不出来
![image](https://github.com/user-attachments/assets/7427c602-4f6b-49f4-84fb-90e31cd6e022)

**Comment by 1vanLuo** [comment]
按照你上面说的增加
import sys,io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
完美解决，谢谢大佬，大佬牛B！
