### ISSUE TITLE
工具对invisible索引解析不到

### ISSUE THREAD

**Issue by mrzhuhelloworld** [ddcw/ibd2sql#35]
mysql8.28版本
ibdsql版本1.5
数据库中的表结构为
![image](https://github.com/user-attachments/assets/d8c048fc-cdd7-47b6-b141-e985c2ebbb19)
ibdsql解析的ddl为
![image](https://github.com/user-attachments/assets/cc861204-c0e2-4e41-bb1f-067e859e6258)

**Comment by ddcw** [comment]
已修复, 感谢反馈!
请下载最新版本验证
`ibd2sql/innodb_page_sdi.py`
```python
.............
                        if not idx['is_visible']:
                                ddl += " /*!80000 INVISIBLE */"
.........
                        is_visible = False if 'is_visible' in idx and (not idx['is_visible']) else True
.........
                                'is_visible':is_visible
```

**Comment by mrzhuhelloworld** [comment]
验证已解决，感谢
