### ISSUE TITLE
解析报错，

### ISSUE THREAD

**Issue by mydbhub** [ddcw/ibd2sql#49]
python3 main.py /data/mysql5726/data/files/bf_files.ibd --sql 
row_format = compressed or its damaged or its mysql 5.7 file

**Comment by zgbgx** [comment]
报相同错误

**Comment by ddcw** [comment]
mysql5环境 得先在mysql8里面创建个一样的表 供ibd2sql获取元数据信息, 然后
```shell
python3 main.py  /mysql5/xxx.ibd  --sdi-table /mysql8/xxx.ibd --mysql5 --sql 
```

文档里面有写5.6  5.7的用法
https://github.com/ddcw/ibd2sql/blob/main/docs/USAGE.md
